services:
  - type: web
    name: job-tracker-api
    runtime: node
    plan: free
    buildCommand: npm install --save-dev @types/express @types/jsonwebtoken && npm run build
    startCommand: node dist/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
